language: node_js
sudo: required
node_js:
- node
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: nSwVbJfdLnOb1dcyytnNMcJuY6DtufFBAyCUQdGyEjA5rZDeGQSeRIHY/cH7K3e+3BKJ4V0vmAZs/QCRhZTsznBiOqlfghkD1yFeikEh+Hbg+wc4uTb2+Aoft9KFmpDhOeYVPWMZWILGR52yUcEQ5t2WprqJsnAp7UiVynmdNGVHyvV582UYPc1+emWQxIkpHKQ4vOZGGIYu7LoQTED+cvnr+1x3MXs7rhZwkSN7/NuXBpyyPN8l5Nd6h+CP4WsvHFlb1nJDB9/3BnpZzWt1cwOsUAH4uxIQtuL2Gls72kz1pkUpSvB6VrdfbaOcCyruwY2p9i9NJiXMOrx6xW7h33Eoy2t36qy8/3O6YLinLk/wqxGNvVjAGqnUwR75SVqlT5aC6Q01ytaZVApIuKfhItsTznW/1n1vDNQJzd5ed4a22LOOe5OYcPi2FD/cGQZ5Tm3sel9ePExO2gWap6yT2y50c6uuSazFvNFn9srLV7XHZAxYxcJf2eAjmN007gLwIR1kEL1e4M4d4JUnxno/+1nDwt9FmsGdmtI0KWKOAD6ke0XTflD+nLLB7jf+5e0f5JEli4/fNm+/xPifLxgC9rvNdl7Vjclcna/4S0LQ8CbuwHbTg+g8Ulh+YAWP3EbPVdR8Y+EvyE3BU4oo5SM6yvtz7p6g+aThVTwD7KHKDRQ=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - dbus
    - gcc-4.8
    - g++-4.8
    - libglib2.0-dev
before_script:
- npm install -g node-gyp
- npm install grunt-cli -g
